project:
  type: website
  
website:
  title: "Datenanalyse in der Biologie"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



