---
title: "Hausaufgabe"
---

### 

Für diese Aufgabe benuzten wir die NHANES-Daten, und zwar *nur* die Probanden im Altersbereich 20 bis 29 Jahre. 

### Aufgabe 1

Berechnen Sie für die Probanden den BMI. Unterscheidet sich der Mittelwert des BMI zwischen den Männern und den Frauen? Ist der Unterschied statistisch signifikant?

### Aufgabe 2

Unterscheidet sich der BMI zwischen den Ethnien? Führen Sie eine Two-way-ANOVA durch für BMI gegen die Faktoren Geschlecht und Ethnie.

### Aufgabe 3

Ermitteln Sie die Anzahl übergewichtiger Frauen und übergewichtiger Männer unter den Probanden. Ein Proband zählt als übergewichtig, wenn der BMI 25 überschreitet. Bestimmen Sie den (prozentualen) Anteil der Übergewichtigen an allen Frauen bzw. Männern. Führen Sie einen statistischen test durch, um zu sehen, ob der Anteil signifikant ist.

### Aufgabe 4

In Aufgabe 1 haben wir den Mittelwert des BMI zwischen den Geschlechtern verglichen, in Aufgabe 3 hingegen den Anteil der Probanden, deren BMI einen vorgegeben Wert überschreitet. Vergleichen Sie die beiden Vorgehensweisen hinsichtlich ihrer Eignung, die Frage zu beantworten, welches Geschlecht mehr von der Adipositas-Epidemie betroffen ist. (Schreiben Sie dazu ein paar Sätze.)

### Aufgabe 5

Visualisieren Sie die Daten, die Sie in Aufgabe 2 untersucht haben, in geeigneter Weise.