# Vorlesung "Datenanalyse in der Biologie"

Dr. Simon Anders, Universität Heidelberg

Wintersemester 2024/25

<small>[QR-Code](qr_url.html)</small>

## Inhalt

- [Einleitung](einleitung.html)
  - ein Beispiel für eine typische Datenanalyse
- [Erste Schritte mit R, Teil I](erste_schritte.html)
  - Bedienung von RStudio
  - Arithmetik
  - Turtle-Grafik
- [Erste Schritte mit R, Teil II](erste_schritte_2.html)
  - Variablen
  - Vektoren und Vektor-Operationen
  - Data-frames
- [Tabellen und Tidyverse: Grundlagen](tidyverse_intro.html)
  - Tidyverse: Grundlagen
  - Tabellen
  - Tidyverse-Verben mutate, arrange, filter, und select
  - Streudiagramme
- [Reduktionen mit Tidyverse](group_by.html)
  - mehr zu group_by und summerize
  - Umgang mit fehlende Daten (`NA`s)
  - zählen mit `sum`
  - logische Operatoren: "nicht", "und", und "oder"
- Joining und Pivoting
  - [Table-Joins](left_join.html)  
  - [Pivoting](pivoting.html)
  - [Hausaufgabe](hausaufgabe_join_pivot.html)
- Histogramme und Verteilungen
  - [Histogramme](histograms.html)
  - [Verteilungen](verteilungen.html)
  - [Hausaufgabe, fällig zum 26.11.](hausaufgabe_verteilungen.html)
- [Inferenz zu Mittelwerten](confint_ttest.html)
  - Standardfehler des Mittelwerts
  - Konfidenzintervalle für Mittelwerte
  - t-Tests
  - gepaarte t-Tests
  - Permutations-Tests
  - [Hausaufgaben](hausaufgabe_ttest.html), fällig zum 3.12.
- [Inferenz zu Anteilen](binom.html)
  - Binomialverteilung
  - Konfidenzintervalle für binomiale Anteile
  - Binomial-Test
  - Fisher-Test
- [Multiples Hypothesentesten](multtest.html)
  - und Diskussion zum p-Wert
- Lineare Modelle
  - [ANOVA](anova.html)
  - [Lineare Regression](linreg.html)
  - [Hausaufgabe](hausaufgabe_bmi.html), fällig zum 17.12.
- [Poisson-Verteilung 1](poisson.html)  
- [Hinweise zu Quarto-Notebooks](standalone.html)
- [Hausaufgabe über die Winterferien](HA_Winter.html)
- [Beispiel-Analyse: LAMP-Test](lamp.html)
- High-throughput sequencing
  - [Übersicht](seq_intro.html)
  - [Präprozessierung von RNA-Seq-Daten](alignment.html)
  - [Hausaufgabe zu RNA-Seq I](HA_rnaseq_1.html)
  - [Erster Blick auf die mausdaten](https://papagei.bioquant.uni-heidelberg.de/simon/dabio23/mouse_first_look.html) (übernommen vom Vorjahr)
  - [Differentielle Gen-Expression](https://papagei.bioquant.uni-heidelberg.de/simon/dabio23/deseq.html)  (übernommen vom Vorjahr)
- [Link zur Vorlesungs-Evaluation](https://uni-heidelberg.evasys.de/evasys/online.php?pswd=FY2S5)
- [Hausaufgabe: "Killing-Assay"](killing.html) (Abgabe bis 27.1.25)
- [Poisson-Verteilung 2](poisson2.html)  

## Musterlösungen zu den Hausaufgaben

(erstellt von den Tutorinnen)

- zur Hausaufgabe [vom 7.11.](Loesung_Hausaufgabe_2024-11-07.html)
- zur Hausaufgabe [vom 24.11.](Loesung_Hausaufgabe_2024-11-14.html)
- zur Hausaufgabe [vom 5.12.](Loesung_Hausaufgabe_2024-11-26.html)
- zur Hausaufgabe [vom 12.12.](Loesung_Hausaufgabe_2024-12-17.html)

## Weitere Links

- [Quellcode](https://github.com/anders-biostat/dabio24) for Quarto notebooks and this site
- [Video-Aufzeichnungen der Vorlesung](https://www.youtube.com/playlist?list=PL3RVGH-VQHwIF56KXWWgCsRLHgcxNVsrE)
- [Literatur zu R und zu Statistik](literature.html)
